name: Starter Workflow first
on:
 pull_request:
  branches: main
jobs:
  call-workflow-passing-data:
   uses: octo-org/example-repo/.github/workflows/build.yml@main
   with:
      config-path: .github/labeler.yml
   secrets: inherit
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: demo2 workflow job
        run: echo This is a demo2 start workflow triggered first workflow
