name: resusable-workflow-caller

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: HoussemDellai/github-actions-course/.github/workflows/080-reusable-workflow-called.yml@main
    with:
      username: sree
    secrets:
      token: ${{ ACTIONS_KEY }}

  call-workflow-B:
    uses: HoussemDellai/github-actions-course/.github/workflows/080-reusable-workflow-called.yml@main
    with:
      username: nina
    secrets:
      token: ${{ ACTIONS_KEY }}
