name: resusable-workflow-caller

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  { }
jobs:
  call-workflow-A:
    uses: sreesar/pr_triggered/.github/workflows/use.yml@main
    with:
      username: sree
    secrets:
      token: ${{ secrets.ACTIONS_KEY }}

  call-workflow-B:
    uses: sreesar/pr_triggered/.github/workflows/use.yml@main
    with:
      username: nina
    secrets:
      token: ${{secrets.ACTIONS_KEY }}
